#ifndef STM32ERROR_H
#define STM32ERROR_H
//USART ERROR
#define USART_REG_INPUT_NULL 1
#define USART_ADDRESS_INVALID 2
#define USART_SEND_INVALID_DATA         3
#define USART_INVALID_INTERRUPT         4
#define USART_INVALID_MODE              5
#define USART_INVALID_TYPE              6

#define ADC_REG_INPUT_NULL             20
#define ADC_INVALID_RESOLUTION         21
#define ADC_INVALID_MODE               22
#define ADC_INVALID_NUMBER_OF_CHANNEL  23
#define ADC_INVALID_CHANNEL            24
#define ADC_INVALID_TRIGGER_DET        25
#define ADC_INVALID_THRESHOLD_VALUE    26
#define ADC_INVALID_SEQUENCE_LENGTH    27
#define ADC_INVALID_SEQUENCE_NUM       28
#define ADC_INVALID_PRESCALER          29
#define ADC_INVALID_CYCLETIME          30
#define ADC_INJECT_SEQUENCE_OVER       31
#define ADC_REGULAR_SEQUENCE_OVER      32

#define GPIO_REG_INPUT_NULL            40
#define GPIO_INVALID_SPEED_MODE        41
#define GPIO_INVALID_PIN               42
#define GPIO_INVALID_PIN_MODE          43
#define GPIO_INVALID_BIT_NUM           44
#define GPIO_INVALID_BIT_VALUE         45
#define GPIO_INVALID_ALT_FUNCTION      46

#define NVIC_INVALID_INTERRUPT_PRIORTY 60
#define NVIC_INVALID_INTERRUPT_NUM     61

#define RCC_INVALID_PORTNAME           80

#define EXTI_REG_INPUT_NULL           100
#define EXTI_INVALID_PIN              101
#define EXTI_INVALID_RISING_TRIGGER_STATUS      102
#define EXTI_INVALID_FALLING_TRIGGER_STATUS      103
#define EXTI_INVALID_MASKED_MODE      104

#define SYSCFG_REG_INPUT_NULL 120
#define SYSCFG_INVALID_EXTI_PORT 121
#define SYSCFG_INVALID_PORT 122
#define SYSCFG_ERROR_CONFIG 123
#endif // STM32ERROR_H
